// This file is automatically generated by `cargo run --bin generate-asts`.
// Do not edit it by hand.

#![allow(
    clippy::doc_lazy_continuation,
    clippy::enum_variant_names,
    clippy::large_enum_variant
)]

use crate::ast::meta::Span;
use derive_generic_visitor::{Drive, DriveMut};
use serde::{Deserialize, Serialize};

use ustr::Ustr;

/// Represents parsed *built-in* inert attributes.
///
/// ## Overview
/// These attributes are markers that guide the compilation process and are never expanded into other code.
/// They persist throughout the compilation phases, from AST to HIR and beyond.
///
/// ## Attribute Processing
/// While attributes are initially parsed by [`rustc_parse`] into [`ast::Attribute`], they still contain raw token streams
/// because different attributes have different internal structures. This enum represents the final,
/// fully parsed form of these attributes, where each variant contains all the information and
/// structure relevant for the specific attribute.
///
/// Some attributes can be applied multiple times to the same item, and they are "collapsed" into a single
/// semantic attribute. For example:
/// ```rust
/// #[repr(C)]
/// #[repr(packed)]
/// struct S { }
/// ```
/// This is equivalent to `#[repr(C, packed)]` and results in a single [`AttributeKind::Repr`] containing
/// both `C` and `packed` annotations. This collapsing happens during parsing and is reflected in the
/// data structures defined in this enum.
///
/// ## Usage
/// These parsed attributes are used throughout the compiler to:
/// - Control code generation (e.g., `#[repr]`)
/// - Mark API stability (`#[stable]`, `#[unstable]`)
/// - Provide documentation (`#[doc]`)
/// - Guide compiler behavior (e.g., `#[allow_internal_unstable]`)
///
/// ## Note on Attribute Organization
/// Some attributes like `InlineAttr`, `OptimizeAttr`, and `InstructionSetAttr` are defined separately
/// from this enum because they are used in specific compiler phases (like code generation) and don't
/// need to persist throughout the entire compilation process. They are typically processed and
/// converted into their final form earlier in the compilation pipeline.
///
/// For example:
/// - `InlineAttr` is used during code generation to control function inlining
/// - `OptimizeAttr` is used to control optimization levels
/// - `InstructionSetAttr` is used for target-specific code generation
///
/// These attributes are handled by their respective compiler passes in the [`rustc_codegen_ssa`] crate
/// and don't need to be preserved in the same way as the attributes in this enum.
///
/// For more details on attribute parsing, see the [`rustc_attr_parsing`] crate.
///
/// [`rustc_parse`]: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/index.html
/// [`rustc_codegen_ssa`]: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_codegen_ssa/index.html
/// [`rustc_attr_parsing`]: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_attr_parsing/index.html
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Drive, DriveMut)]
#[cfg_attr(feature = "charon_on_charon", charon::rename("BuiltinAttr"))]
#[cfg_attr(feature = "charon_on_charon", charon::variants_prefix("BuiltinAttr"))]
pub enum BuiltinAttr {
    /// Represents `#[automatically_derived]`
    AutomaticallyDerived,
    /// Represents `#[cold]`.
    Cold,
    /// Implementation detail of `#[eii]`
    EiiDeclaration(EiiDecl),
    /// Implementation detail of `#[eii]`
    EiiImpls(Vec<EiiImpl>),
    /// Represents `#[fundamental]`.
    Fundamental,
    /// Represents `#[ignore]`
    Ignore {
        span: Span,
        /// ignore can optionally have a reason: `#[ignore = "reason this is ignored"]`
        reason: Option<Ustr>,
    },
    /// Represents `#[inline]` and `#[rustc_force_inline]`.
    Inline(InlineAttr, Span),
    /// Represents `#[lang]`
    Lang(LangItem),
    /// Represents [`#[may_dangle]`](https://std-dev-guide.rust-lang.org/tricky/may-dangle.html).
    MayDangle(Span),
    /// Represents `#[naked]`
    Naked(Span),
    /// Represents `#[no_link]`
    NoLink,
    /// Represents `#[no_mangle]`
    NoMangle(Span),
    /// Represents `#[non_exhaustive]`
    NonExhaustive(Span),
    /// Represents `#[optimize(size|speed)]`
    Optimize(OptimizeAttr, Span),
    /// Represents `#[rustc_diagnostic_item]`
    RustcDiagnosticItem(Ustr),
    /// Represents `#[rustc_intrinsic]`
    RustcIntrinsic,
    /// Represents `#[target_feature(enable = "...")]` and
    /// `#[unsafe(force_target_feature(enable = "...")]`.
    TargetFeature {
        features: Vec<(Ustr, Span)>,
        attr_span: Span,
        was_forced: bool,
    },
    /// Represents `#[track_caller]`
    TrackCaller(Span),
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Drive, DriveMut)]
#[cfg_attr(feature = "charon_on_charon", charon::rename("BuiltinAttrEiiDecl"))]
pub struct EiiDecl {
    pub foreign_item: Ustr,
    /// whether or not it is unsafe to implement this EII
    pub impl_unsafe: bool,
    pub name: Ident,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Drive, DriveMut)]
#[cfg_attr(feature = "charon_on_charon", charon::rename("BuiltinAttrEiiImpl"))]
pub struct EiiImpl {
    pub resolution: EiiImplResolution,
    pub impl_marked_unsafe: bool,
    pub span: Span,
    pub inner_span: Span,
    pub is_default: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Drive, DriveMut)]
#[cfg_attr(feature = "charon_on_charon", charon::rename("BuiltinAttrIdent"))]
pub struct Ident {
    /// `name` should never be the empty symbol. If you are considering that,
    /// you are probably conflating "empty identifier with "no identifier" and
    /// you should use `Option<Ident>` instead.
    /// Trying to construct an `Ident` with an empty name will trigger debug assertions.
    pub name: Ustr,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Drive, DriveMut)]
#[cfg_attr(feature = "charon_on_charon", charon::rename("BuiltinAttrInlineAttr"))]
#[cfg_attr(
    feature = "charon_on_charon",
    charon::variants_prefix("BuiltinAttrInlineAttr")
)]
pub enum InlineAttr {
    None,
    Hint,
    Always,
    Never,
    /// `#[rustc_force_inline]` forces inlining to happen in the MIR inliner - it reports an error
    /// if the inlining cannot happen. It is limited to only free functions so that the calls
    /// can always be resolved.
    Force {
        attr_span: Span,
        reason: Option<Ustr>,
    },
}

/// A representation of all the valid lang items in Rust.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Drive, DriveMut)]
#[cfg_attr(feature = "charon_on_charon", charon::rename("BuiltinAttrLangItem"))]
#[cfg_attr(
    feature = "charon_on_charon",
    charon::variants_prefix("BuiltinAttrLangItem")
)]
pub enum LangItem {
    ///The `sized` lang item.
    Sized,
    ///The `meta_sized` lang item.
    MetaSized,
    ///The `pointee_sized` lang item.
    PointeeSized,
    ///The `unsize` lang item.
    Unsize,
    ///The `mem_align_const` lang item.
    AlignOf,
    ///The `mem_size_const` lang item.
    SizeOf,
    ///The `offset_of` lang item.
    OffsetOf,
    ///The `structural_peq` lang item.
    /// Trait injected by `#[derive(PartialEq)]`, (i.e. "Partial EQ").
    StructuralPeq,
    ///The `copy` lang item.
    Copy,
    ///The `clone` lang item.
    Clone,
    ///The `clone_fn` lang item.
    CloneFn,
    ///The `use_cloned` lang item.
    UseCloned,
    ///The `trivial_clone` lang item.
    TrivialClone,
    ///The `sync` lang item.
    Sync,
    ///The `discriminant_kind` lang item.
    DiscriminantKind,
    ///The `discriminant_type` lang item.
    /// The associated item of the `DiscriminantKind` trait.
    Discriminant,
    ///The `pointee_trait` lang item.
    PointeeTrait,
    ///The `metadata_type` lang item.
    Metadata,
    ///The `dyn_metadata` lang item.
    DynMetadata,
    ///The `freeze` lang item.
    Freeze,
    ///The `unsafe_unpin` lang item.
    UnsafeUnpin,
    ///The `fn_ptr_trait` lang item.
    FnPtrTrait,
    ///The `fn_ptr_addr` lang item.
    FnPtrAddr,
    ///The `drop` lang item.
    Drop,
    ///The `destruct` lang item.
    Destruct,
    ///The `async_drop` lang item.
    AsyncDrop,
    ///The `async_drop_in_place` lang item.
    AsyncDropInPlace,
    ///The `coerce_unsized` lang item.
    CoerceUnsized,
    ///The `dispatch_from_dyn` lang item.
    DispatchFromDyn,
    ///The `transmute_opts` lang item.
    TransmuteOpts,
    ///The `transmute_trait` lang item.
    TransmuteTrait,
    ///The `add` lang item.
    Add,
    ///The `sub` lang item.
    Sub,
    ///The `mul` lang item.
    Mul,
    ///The `div` lang item.
    Div,
    ///The `rem` lang item.
    Rem,
    ///The `neg` lang item.
    Neg,
    ///The `not` lang item.
    Not,
    ///The `bitxor` lang item.
    BitXor,
    ///The `bitand` lang item.
    BitAnd,
    ///The `bitor` lang item.
    BitOr,
    ///The `shl` lang item.
    Shl,
    ///The `shr` lang item.
    Shr,
    ///The `add_assign` lang item.
    AddAssign,
    ///The `sub_assign` lang item.
    SubAssign,
    ///The `mul_assign` lang item.
    MulAssign,
    ///The `div_assign` lang item.
    DivAssign,
    ///The `rem_assign` lang item.
    RemAssign,
    ///The `bitxor_assign` lang item.
    BitXorAssign,
    ///The `bitand_assign` lang item.
    BitAndAssign,
    ///The `bitor_assign` lang item.
    BitOrAssign,
    ///The `shl_assign` lang item.
    ShlAssign,
    ///The `shr_assign` lang item.
    ShrAssign,
    ///The `index` lang item.
    Index,
    ///The `index_mut` lang item.
    IndexMut,
    ///The `unsafe_cell` lang item.
    UnsafeCell,
    ///The `unsafe_pinned` lang item.
    UnsafePinned,
    ///The `va_arg_safe` lang item.
    VaArgSafe,
    ///The `va_list` lang item.
    VaList,
    ///The `deref` lang item.
    Deref,
    ///The `deref_mut` lang item.
    DerefMut,
    ///The `deref_pure` lang item.
    DerefPure,
    ///The `deref_target` lang item.
    DerefTarget,
    ///The `receiver` lang item.
    Receiver,
    ///The `receiver_target` lang item.
    ReceiverTarget,
    ///The `legacy_receiver` lang item.
    LegacyReceiver,
    ///The `Fn` lang item.
    Fn,
    ///The `fn_mut` lang item.
    FnMut,
    ///The `fn_once` lang item.
    FnOnce,
    ///The `async_fn` lang item.
    AsyncFn,
    ///The `async_fn_mut` lang item.
    AsyncFnMut,
    ///The `async_fn_once` lang item.
    AsyncFnOnce,
    ///The `async_fn_once_output` lang item.
    AsyncFnOnceOutput,
    ///The `call_once_future` lang item.
    CallOnceFuture,
    ///The `call_ref_future` lang item.
    CallRefFuture,
    ///The `async_fn_kind_helper` lang item.
    AsyncFnKindHelper,
    ///The `async_fn_kind_upvars` lang item.
    AsyncFnKindUpvars,
    ///The `fn_once_output` lang item.
    FnOnceOutput,
    ///The `iterator` lang item.
    Iterator,
    ///The `fused_iterator` lang item.
    FusedIterator,
    ///The `future_trait` lang item.
    Future,
    ///The `future_output` lang item.
    FutureOutput,
    ///The `async_iterator` lang item.
    AsyncIterator,
    ///The `coroutine_state` lang item.
    CoroutineState,
    ///The `coroutine` lang item.
    Coroutine,
    ///The `coroutine_return` lang item.
    CoroutineReturn,
    ///The `coroutine_yield` lang item.
    CoroutineYield,
    ///The `coroutine_resume` lang item.
    CoroutineResume,
    ///The `unpin` lang item.
    Unpin,
    ///The `pin` lang item.
    Pin,
    ///The `Ordering` lang item.
    OrderingEnum,
    ///The `eq` lang item.
    PartialEq,
    ///The `partial_ord` lang item.
    PartialOrd,
    ///The `c_void` lang item.
    CVoid,
    ///The `type_info` lang item.
    Type,
    ///The `type_id` lang item.
    TypeId,
    ///The `panic` lang item.
    Panic,
    ///The `panic_nounwind` lang item.
    PanicNounwind,
    ///The `panic_fmt` lang item.
    PanicFmt,
    ///The `panic_display` lang item.
    PanicDisplay,
    ///The `const_panic_fmt` lang item.
    ConstPanicFmt,
    ///The `panic_bounds_check` lang item.
    PanicBoundsCheck,
    ///The `panic_misaligned_pointer_dereference` lang item.
    PanicMisalignedPointerDereference,
    ///The `panic_info` lang item.
    PanicInfo,
    ///The `panic_location` lang item.
    PanicLocation,
    ///The `panic_impl` lang item.
    PanicImpl,
    ///The `panic_cannot_unwind` lang item.
    PanicCannotUnwind,
    ///The `panic_in_cleanup` lang item.
    PanicInCleanup,
    ///The `panic_const_add_overflow` lang item.
    /// Constant panic messages, used for codegen of MIR asserts.
    PanicAddOverflow,
    ///The `panic_const_sub_overflow` lang item.
    PanicSubOverflow,
    ///The `panic_const_mul_overflow` lang item.
    PanicMulOverflow,
    ///The `panic_const_div_overflow` lang item.
    PanicDivOverflow,
    ///The `panic_const_rem_overflow` lang item.
    PanicRemOverflow,
    ///The `panic_const_neg_overflow` lang item.
    PanicNegOverflow,
    ///The `panic_const_shr_overflow` lang item.
    PanicShrOverflow,
    ///The `panic_const_shl_overflow` lang item.
    PanicShlOverflow,
    ///The `panic_const_div_by_zero` lang item.
    PanicDivZero,
    ///The `panic_const_rem_by_zero` lang item.
    PanicRemZero,
    ///The `panic_const_coroutine_resumed` lang item.
    PanicCoroutineResumed,
    ///The `panic_const_async_fn_resumed` lang item.
    PanicAsyncFnResumed,
    ///The `panic_const_async_gen_fn_resumed` lang item.
    PanicAsyncGenFnResumed,
    ///The `panic_const_gen_fn_none` lang item.
    PanicGenFnNone,
    ///The `panic_const_coroutine_resumed_panic` lang item.
    PanicCoroutineResumedPanic,
    ///The `panic_const_async_fn_resumed_panic` lang item.
    PanicAsyncFnResumedPanic,
    ///The `panic_const_async_gen_fn_resumed_panic` lang item.
    PanicAsyncGenFnResumedPanic,
    ///The `panic_const_gen_fn_none_panic` lang item.
    PanicGenFnNonePanic,
    ///The `panic_null_pointer_dereference` lang item.
    PanicNullPointerDereference,
    ///The `panic_invalid_enum_construction` lang item.
    PanicInvalidEnumConstruction,
    ///The `panic_const_coroutine_resumed_drop` lang item.
    PanicCoroutineResumedDrop,
    ///The `panic_const_async_fn_resumed_drop` lang item.
    PanicAsyncFnResumedDrop,
    ///The `panic_const_async_gen_fn_resumed_drop` lang item.
    PanicAsyncGenFnResumedDrop,
    ///The `panic_const_gen_fn_none_drop` lang item.
    PanicGenFnNoneDrop,
    ///The `begin_panic` lang item.
    /// libstd panic entry point. Necessary for const eval to be able to catch it
    BeginPanic,
    ///The `format_argument` lang item.
    FormatArgument,
    ///The `format_arguments` lang item.
    FormatArguments,
    ///The `drop_glue` lang item.
    DropGlue,
    ///The `alloc_layout` lang item.
    AllocLayout,
    ///The `start` lang item.
    /// For all binary crates without `#![no_main]`, Rust will generate a "main" function.
    /// The exact name and signature are target-dependent. The "main" function will invoke
    /// this lang item, passing it the `argc` and `argv` (or null, if those don't exist
    /// on the current target) as well as the user-defined `fn main` from the binary crate.
    Start,
    ///The `eh_personality` lang item.
    EhPersonality,
    ///The `eh_catch_typeinfo` lang item.
    EhCatchTypeinfo,
    ///The `compiler_move` lang item.
    CompilerMove,
    ///The `compiler_copy` lang item.
    CompilerCopy,
    ///The `owned_box` lang item.
    OwnedBox,
    ///The `global_alloc_ty` lang item.
    GlobalAlloc,
    ///The `phantom_data` lang item.
    PhantomData,
    ///The `manually_drop` lang item.
    ManuallyDrop,
    ///The `maybe_dangling` lang item.
    MaybeDangling,
    ///The `bikeshed_guaranteed_no_drop` lang item.
    BikeshedGuaranteedNoDrop,
    ///The `maybe_uninit` lang item.
    MaybeUninit,
    ///The `termination` lang item.
    Termination,
    ///The `Try` lang item.
    Try,
    ///The `tuple_trait` lang item.
    Tuple,
    ///The `slice_len_fn` lang item.
    SliceLen,
    ///The `from_residual` lang item.
    TryTraitFromResidual,
    ///The `from_output` lang item.
    TryTraitFromOutput,
    ///The `branch` lang item.
    TryTraitBranch,
    ///The `from_yeet` lang item.
    TryTraitFromYeet,
    ///The `into_try_type` lang item.
    ResidualIntoTryType,
    ///The `coerce_pointee_validated` lang item.
    CoercePointeeValidated,
    ///The `const_param_ty` lang item.
    ConstParamTy,
    ///The `Poll` lang item.
    Poll,
    ///The `Ready` lang item.
    PollReady,
    ///The `Pending` lang item.
    PollPending,
    ///The `AsyncGenReady` lang item.
    AsyncGenReady,
    ///The `AsyncGenPending` lang item.
    AsyncGenPending,
    ///The `AsyncGenFinished` lang item.
    AsyncGenFinished,
    ///The `ResumeTy` lang item.
    ResumeTy,
    ///The `get_context` lang item.
    GetContext,
    ///The `Context` lang item.
    Context,
    ///The `poll` lang item.
    FuturePoll,
    ///The `async_iterator_poll_next` lang item.
    AsyncIteratorPollNext,
    ///The `into_async_iter_into_iter` lang item.
    IntoAsyncIterIntoIter,
    ///The `Option` lang item.
    Option,
    ///The `Some` lang item.
    OptionSome,
    ///The `None` lang item.
    OptionNone,
    ///The `Ok` lang item.
    ResultOk,
    ///The `Err` lang item.
    ResultErr,
    ///The `Continue` lang item.
    ControlFlowContinue,
    ///The `Break` lang item.
    ControlFlowBreak,
    ///The `into_future` lang item.
    IntoFutureIntoFuture,
    ///The `into_iter` lang item.
    IntoIterIntoIter,
    ///The `next` lang item.
    IteratorNext,
    ///The `new_unchecked` lang item.
    PinNewUnchecked,
    ///The `RangeFrom` lang item.
    RangeFrom,
    ///The `RangeFull` lang item.
    RangeFull,
    ///The `RangeInclusive` lang item.
    RangeInclusiveStruct,
    ///The `range_inclusive_new` lang item.
    RangeInclusiveNew,
    ///The `Range` lang item.
    Range,
    ///The `RangeToInclusive` lang item.
    RangeToInclusive,
    ///The `RangeTo` lang item.
    RangeTo,
    ///The `RangeMax` lang item.
    RangeMax,
    ///The `RangeMin` lang item.
    RangeMin,
    ///The `RangeSub` lang item.
    RangeSub,
    ///The `RangeFromCopy` lang item.
    RangeFromCopy,
    ///The `RangeCopy` lang item.
    RangeCopy,
    ///The `RangeInclusiveCopy` lang item.
    RangeInclusiveCopy,
    ///The `RangeToInclusiveCopy` lang item.
    RangeToInclusiveCopy,
    ///The `String` lang item.
    String,
    ///The `CStr` lang item.
    CStr,
    ///The `contract_build_check_ensures` lang item.
    ContractBuildCheckEnsures,
    ///The `contract_check_requires` lang item.
    ContractCheckRequires,
    ///The `default_trait4` lang item.
    DefaultTrait4,
    ///The `default_trait3` lang item.
    DefaultTrait3,
    ///The `default_trait2` lang item.
    DefaultTrait2,
    ///The `default_trait1` lang item.
    DefaultTrait1,
    ///The `contract_check_ensures` lang item.
    ContractCheckEnsures,
    ///The `reborrow` lang item.
    Reborrow,
    ///The `coerce_shared` lang item.
    CoerceShared,
    ///The `field_representing_type` lang item.
    FieldRepresentingType,
    ///The `field` lang item.
    Field,
    ///The `field_base` lang item.
    FieldBase,
    ///The `field_type` lang item.
    FieldType,
    ///The `field_offset` lang item.
    FieldOffset,
    ///The `From` lang item.
    From,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Drive, DriveMut)]
#[cfg_attr(
    feature = "charon_on_charon",
    charon::rename("BuiltinAttrOptimizeAttr")
)]
#[cfg_attr(
    feature = "charon_on_charon",
    charon::variants_prefix("BuiltinAttrOptimizeAttr")
)]
pub enum OptimizeAttr {
    /// No `#[optimize(..)]` attribute
    Default,
    /// `#[optimize(none)]`
    DoNotOptimize,
    /// `#[optimize(speed)]`
    Speed,
    /// `#[optimize(size)]`
    Size,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Drive, DriveMut)]
#[cfg_attr(
    feature = "charon_on_charon",
    charon::rename("BuiltinAttrEiiImplResolution")
)]
#[cfg_attr(
    feature = "charon_on_charon",
    charon::variants_prefix("BuiltinAttrEiiImplResolution")
)]
pub enum EiiImplResolution {
    /// Usually, finding the extern item that an EII implementation implements means finding
    /// the defid of the associated attribute macro, and looking at *its* attributes to find
    /// what foreign item its associated with.
    Macro(Ustr),
    /// Sometimes though, we already know statically and can skip some name resolution.
    /// Stored together with the eii's name for diagnostics.
    Known(EiiDecl),
    /// For when resolution failed, but we want to continue compilation
    Error(Ustr),
}
