//! Implementations for [crate::ullbc_ast]
use crate::ids::Vector;
use crate::meta::Span;
use crate::types::*;
use crate::ullbc_ast::*;
use crate::values::*;
use macros::make_generic_in_borrows;
use take_mut::take;

impl SwitchTargets {
    pub fn get_targets(&self) -> Vec<BlockId> {
        match self {
            SwitchTargets::If(then_tgt, else_tgt) => {
                vec![*then_tgt, *else_tgt]
            }
            SwitchTargets::SwitchInt(_, targets, otherwise) => {
                let mut all_targets = vec![];
                for (_, target) in targets {
                    all_targets.push(*target);
                }
                all_targets.push(*otherwise);
                all_targets
            }
        }
    }
}

impl Statement {
    pub fn new(span: Span, content: RawStatement) -> Self {
        Statement { span, content }
    }
}

impl Terminator {
    pub fn new(span: Span, content: RawTerminator) -> Self {
        Terminator { span, content }
    }
}

impl BlockData {
    /// Visit the operands in an rvalue and generate statements.
    /// Used below in [BlockData::transform_operands].
    /// TODO: use visitors
    fn transform_rvalue_operands<F: FnMut(&Span, &mut Vec<Statement>, &mut Operand)>(
        span: &Span,
        nst: &mut Vec<Statement>,
        rval: &mut Rvalue,
        f: &mut F,
    ) {
        match rval {
            Rvalue::Use(op) | Rvalue::UnaryOp(_, op) => f(span, nst, op),
            Rvalue::BinaryOp(_, o1, o2) => {
                f(span, nst, o1);
                f(span, nst, o2);
            }
            Rvalue::Aggregate(_, ops) => {
                for op in ops {
                    f(span, nst, op);
                }
            }
            Rvalue::Repeat(op, _, _) => {
                f(span, nst, op);
            }
            Rvalue::Global(..) | Rvalue::Discriminant(..) | Rvalue::Ref(_, _) | Rvalue::Len(..) => {
                // No operands: nothing to do
            }
        }
    }

    /// See [body_transform_operands]
    pub fn transform_operands<F: FnMut(&Span, &mut Vec<Statement>, &mut Operand)>(
        mut self,
        f: &mut F,
    ) -> Self {
        // The new vector of statements
        let mut nst = vec![];

        // Explore the operands in the statements
        for mut st in self.statements {
            let span = &st.span;
            match &mut st.content {
                RawStatement::Assign(_, rvalue) => {
                    BlockData::transform_rvalue_operands(span, &mut nst, rvalue, f);
                }
                RawStatement::FakeRead(_)
                | RawStatement::SetDiscriminant(_, _)
                | RawStatement::StorageDead(_)
                | RawStatement::Deinit(_)
                | RawStatement::Error(_) => {
                    // No operands: nothing to do
                }
            }
            // Add the statement to the vector of statements
            nst.push(st)
        }

        // Explore the terminator
        let span = &self.terminator.span;
        match &mut self.terminator.content {
            RawTerminator::Switch { discr, targets: _ } => {
                f(span, &mut nst, discr);
            }
            RawTerminator::Call { call, target: _ } => {
                for arg in &mut call.args {
                    f(span, &mut nst, arg);
                }
            }
            RawTerminator::Assert {
                cond,
                expected: _,
                target: _,
            } => {
                f(span, &mut nst, cond);
            }
            RawTerminator::Panic
            | RawTerminator::Return
            | RawTerminator::Unreachable
            | RawTerminator::Goto { target: _ }
            | RawTerminator::Drop {
                place: _,
                target: _,
            } => {
                // Nothing to do
            }
        };

        // Update the vector of statements
        self.statements = nst;

        // Return
        self
    }
}

/// Transform a body by applying a function to its operands, and
/// inserting the statements generated by the operands at the end of the
/// block.
/// Useful to implement a pass on operands (see e.g., [crate::extract_global_assignments]).
///
/// The span argument given to `f` is the span argument of the [Terminator]
/// containing the operand. `f` should explore the operand it receives, and
/// push statements to the vector it receives as input.
pub fn body_transform_operands<F: FnMut(&Span, &mut Vec<Statement>, &mut Operand)>(
    blocks: &mut Vector<BlockId, BlockData>,
    f: &mut F,
) {
    for block in blocks.iter_mut() {
        take(block, |b| b.transform_operands(f));
    }
}

// Derive two implementations at once: one which uses shared borrows, and one
// which uses mutable borrows.
// Generates the traits: `SharedAstVisitor` and `MutAstVisitor`.
make_generic_in_borrows! {

/// A visitor for the ULLBC AST
///
/// Remark: we can't call the "super" method when reimplementing a method
/// (unlike what can be done in, say, OCaml). This makes imlementing visitors
/// slightly awkward, and is the reason why we split some visit functions in two:
/// a "standard" version to be overriden, and a "default" version which should
/// not be overriden and gives access to the "super" method.
///
/// TODO: implement macros to automatically derive visitors.
pub trait AstVisitor: crate::expressions::ExprVisitor {
    fn visit_block_data(&mut self, block: &BlockData) {
        for st in &block.statements {
            self.visit_statement(st);
        }
        self.visit_terminator(&block.terminator);
    }

    fn visit_statement(&mut self, st: &Statement) {
        self.visit_span(&st.span);
        self.visit_raw_statement(&st.content);
    }

    fn visit_raw_statement(&mut self, st: &RawStatement) {
        self.default_visit_raw_statement(st);
    }

    fn default_visit_raw_statement(&mut self, st: &RawStatement) {
        use RawStatement::*;
        match st {
            Assign(p, rv) => self.visit_assign(p, rv),
            FakeRead(p) => self.visit_fake_read(p),
            SetDiscriminant(p, vid) => self.visit_set_discriminant(p, vid),
            StorageDead(vid) => self.visit_storage_dead(vid),
            Deinit(p) => self.visit_deinit(p),
            Error(s) => self.visit_error(s),
        }
    }

    fn visit_assign(&mut self, p: &Place, rv: &Rvalue) {
        self.visit_place(p);
        self.visit_rvalue(rv);
    }

    fn visit_fake_read(&mut self, p: &Place) {
        self.visit_place(p);
    }

    fn visit_set_discriminant(&mut self, p: &Place, _vid: &VariantId) {
        self.visit_place(p);
    }

    fn visit_storage_dead(&mut self, vid: &VarId) {
        self.visit_var_id(vid);
    }

    fn visit_deinit(&mut self, p: &Place) {
        self.visit_place(p);
    }

    fn visit_error(&mut self, s: &String) {}

    fn visit_terminator(&mut self, st: &Terminator) {
        self.visit_span(&st.span);
        self.visit_raw_terminator(&st.content);
    }

    fn visit_span(&mut self, st: &Span) {}

    fn default_visit_raw_terminator(&mut self, st: &RawTerminator) {
        use RawTerminator::*;
        match st {
            Goto { target } => self.visit_goto(target),
            Switch { discr, targets } => {
                self.visit_switch(discr, targets);
            }
            Panic => self.visit_panic(),
            Return => self.visit_return(),
            Unreachable => self.visit_unreachable(),
            Drop { place, target } => {
                self.visit_drop(place, target);
            }
            Call { call, target } => {
                self.visit_call_statement(call, target);
            }
            Assert {
                cond,
                expected,
                target,
            } => {
                self.visit_assert(cond, expected, target);
            }
        }
    }

    fn visit_raw_terminator(&mut self, st: &RawTerminator) {
        self.default_visit_raw_terminator(st);
    }

    fn visit_goto(&mut self, target: &BlockId) {
        self.visit_block_id(target)
    }

    fn visit_switch(&mut self, discr: &Operand, targets: &SwitchTargets) {
        self.visit_operand(discr);
        self.visit_switch_targets(targets);
    }

    fn visit_panic(&mut self) {}

    fn visit_return(&mut self) {}

    fn visit_unreachable(&mut self) {}

    fn visit_drop(&mut self, place: &Place, target: &BlockId) {
        self.visit_place(place);
        self.visit_block_id(target);
    }

    fn visit_call_statement(&mut self, call: &Call, target: &BlockId) {
        self.visit_call(call);
        self.visit_block_id(target);
    }

    fn visit_assert(&mut self, cond: &Operand, expected: &bool, target: &BlockId) {
        self.visit_operand(cond);
        self.visit_block_id(target);
    }

    fn visit_block_id(&mut self, id: &BlockId) {}

    fn visit_switch_targets(&mut self, targets: &SwitchTargets) {
        use SwitchTargets::*;
        match targets {
            If(then_id, else_id) => self.visit_if(then_id, else_id),
            SwitchInt(int_ty, branches, otherwise) => {
                self.visit_switch_int(int_ty, branches, otherwise)
            }
        }
    }

    fn visit_if(&mut self, then_id: &BlockId, else_id: &BlockId) {
        self.visit_block_id(then_id);
        self.visit_block_id(else_id);
    }

    fn visit_switch_int(
        &mut self,
        int_ty: &IntegerTy,
        branches: &Vec<(ScalarValue, BlockId)>,
        otherwise: &BlockId,
    ) {
        for (_, br) in branches {
            self.visit_block_id(br);
        }
        self.visit_block_id(otherwise);
    }
}

} // make_generic_in_borrows
