[package]
name = "tests"
version = "0.1.0"
authors = ["Son Ho <hosonmarc@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.59"
serde = { version = "1.0.117", features = ["derive"] }
log = "0.4.14"
env_logger = "0.8.4"
