//! Inline assembly inside a function body.
//!
//! See the [Rust Reference](https://doc.rust-lang.org/reference/inline-assembly.html) for the
//! meaning of operands and options.
use crate::ast::*;
use derive_generic_visitor::{Drive, DriveMut, DriveTwo};
use macros::EnumIsA;
use serde_state::{DeserializeState, SerializeState};
use ustr::Ustr;

generate_index_type!(AsmOperandId, "AsmOperand");

/// Contents of an inline assembly block.
#[derive(Debug, Clone, PartialEq, Eq)]
#[derive(SerializeState, DeserializeState, Drive, DriveMut, DriveTwo)]
pub struct InlineAsm {
    /// Whether this is an `asm!` or `naked_asm!` assembly block.
    pub kind: AsmKind,
    /// The assembly code, parsed into a series of text fragments interspersed with placeholders.
    pub template: Vec<AsmTemplatePiece>,
    /// Input/outputs of the asm block. Not all of them may be referred to by placeholders, e.g.
    /// explicit register operands may not.
    pub operands: IndexVec<AsmOperandId, AsmOperand>,
    /// The flags set in `options(...)`.
    pub options: AsmOptions,
}

/// The kind of assembly block this is.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[derive(EnumIsA)]
#[derive(SerializeState, DeserializeState, Drive, DriveMut, DriveTwo)]
pub enum AsmKind {
    /// Assembly generated by the `asm!` macro.
    Asm,
    /// Assembly generated by the `naked_asm!` macro. This forms the entire function body and only
    /// accepts `const` and `sym` operands.
    NakedAsm,
}

/// A fragment of assembly code.
#[derive(Debug, Clone, PartialEq, Eq)]
#[derive(SerializeState, DeserializeState, Drive, DriveMut, DriveTwo)]
#[cfg_attr(feature = "charon_on_charon", charon::variants_prefix("AsmTemplate"))]
pub enum AsmTemplatePiece {
    /// Literal assembly text.
    Text(#[serde_state(stateless)] Ustr),
    /// Substitutes an operand, optionally with an architecture-specific register modifier.
    Placeholder {
        operand_id: AsmOperandId,
        modifier: Option<char>,
        span: Span,
    },
}

/// An explicit register (such as `"rax"`) or a register class (such as `reg`).
#[derive(Debug, Clone, PartialEq, Eq)]
#[derive(SerializeState, DeserializeState, Drive, DriveMut, DriveTwo)]
#[serde_state(stateless)]
pub enum AsmRegister {
    Explicit(Ustr),
    Class(Ustr),
}

/// An operand supplied to inline assembly.
#[derive(Debug, Clone, PartialEq, Eq)]
#[derive(SerializeState, DeserializeState, Drive, DriveMut, DriveTwo)]
pub enum AsmOperand {
    /// `in(reg) value`: read `value` into the register before running the assembly.
    In { reg: AsmRegister, value: Operand },
    /// `out(reg) place` or `lateout(reg) place`: the contents of the register are written to
    /// `place` at the end of the block, or discarded if `place` is `None` (essentially acting as a
    /// clobber).
    Out {
        reg: AsmRegister,
        late: bool,
        place: Option<Place>,
    },
    /// `inout(reg) value => place` or `inlateout(reg) value => place`. Combines `in(reg) value`
    /// and `out/lateout(reg) place`. The input and output places may be the same.
    InOut {
        reg: AsmRegister,
        late: bool,
        in_value: Operand,
        out_place: Option<Place>,
    },
    /// An integer constant substituted into the template.
    Const(ConstantExpr),
    /// A function symbol substituted into the template.
    SymFn(FnPtr),
    /// A static symbol substituted into the template.
    SymStatic(GlobalDeclRef),
    /// The address of a block that the assembly may jump to. That `BranchId` corresponds to the
    /// targets listed in [`ullbc_ast::TerminatorKind::InlineAsm`] and
    /// [`llbc_ast::StatementKind::InlineAsm`].
    Label(BranchId),
}

/// The flags set in `options(...)`. These flags constrain the assembly's effects; they do not
/// describe instructions in the template itself.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[derive(SerializeState, DeserializeState, Drive, DriveMut, DriveTwo)]
pub struct AsmOptions {
    /// The assembly code has no side effects, must eventually return, and its outputs depend only
    /// on its direct inputs or values read from memory.
    pub pure: bool,
    /// The assembly code does not read from or write to any memory accessible outside of the
    /// assembly code.
    pub nomem: bool,
    /// The assembly code does not write to any memory accessible outside of the assembly code.
    pub readonly: bool,
    /// The assembly code does not modify the flags register.
    pub preserves_flags: bool,
    /// The assembly code does not fall through; it may still jump to label blocks.
    pub noreturn: bool,
    /// The assembly code does not push data to the stack, or write to the stack red-zone.
    pub nostack: bool,
    /// Only valid on x86; causes the assembler to use the .att_syntax prefix mode of the GNU assembler.
    pub att_syntax: bool,
    /// Allows unwinding out of an `asm!` block (unstable, see
    /// https://github.com/rust-lang/rust/issues/93334). `naked_asm!` may unwind regardless of this
    /// option.
    pub may_unwind: bool,
}
