//! Implements expressions: paths, operands, rvalues, lvalues
use crate::ast::*;
use derive_generic_visitor::{Drive, DriveMut, DriveTwo};
use macros::{EnumAsGetters, EnumIsA, EnumToGetters, VariantIndexArity, VariantName};
use serde::{Deserialize, Serialize};
use serde_state::{DeserializeState, SerializeState};
use std::vec::Vec;

/// An expression that evaluates to a value. This is the RHS of an assignment.
#[derive(
    Debug,
    PartialEq,
    Eq,
    Clone,
    EnumToGetters,
    EnumAsGetters,
    EnumIsA,
    SerializeState,
    DeserializeState,
    Drive,
    DriveMut,
    DriveTwo,
)]
pub enum Rvalue {
    /// Lifts an operand as an rvalue.
    Use(Operand, WithRetag),
    /// Takes a reference to the given place.
    /// The `Operand` refers to the init value of the metadata, it is `()` if no metadata
    #[cfg_attr(feature = "charon_on_charon", charon::rename("RvRef"))]
    Ref {
        place: Place,
        #[serde_state(stateless)]
        kind: BorrowKind,
        ptr_metadata: Operand,
    },
    /// Takes a raw pointer with the given mutability to the given place. This is generated by
    /// pointer casts like `&v as *const _` or raw borrow expressions like `&raw const v.`
    /// Like `Ref`, the `Operand` refers to the init value of the metadata, it is `()` if no metadata.
    RawPtr {
        place: Place,
        kind: RefKind,
        ptr_metadata: Operand,
    },
    /// Binary operations (note that we merge "checked" and "unchecked" binops)
    BinaryOp(BinOp, Operand, Operand),
    /// Unary operation (e.g. not, neg)
    UnaryOp(UnOp, Operand),
    /// Nullary operation (e.g. `size_of`)
    NullaryOp(NullOp, Ty),
    /// Discriminant read. Reads the discriminant value of an enum. The place must have the type of
    /// an enum. The discriminant in question is the one in the `discriminant` field of the
    /// corresponding `Variant`. This can be different than the value stored in memory (called
    /// `tag`); that one is described by [`Discriminator`] and [`VariantLayout::tagger`].
    Discriminant(Place),
    /// Creates an aggregate value, like a tuple, a struct or an enum:
    /// ```text
    /// l = List::Cons { value:x, tail:tl };
    /// ```
    /// Note that in some MIR passes (like optimized MIR), aggregate values are
    /// decomposed, like below:
    /// ```text
    /// (l as List::Cons).value = x;
    /// (l as List::Cons).tail = tl;
    /// ```
    /// Because we may want to plug our translation mechanism at various
    /// places, we need to take both into accounts in the translation and in
    /// our semantics. Aggregate value initialization is easy, you might want
    /// to have a look at expansion of `Bottom` values for explanations about the
    /// other case.
    ///
    /// Remark: in case of closures, the aggregated value groups the closure id
    /// together with its state.
    Aggregate(AggregateKind, Vec<Operand>),
    /// Length of a place of type `[T]` or `[T; N]`. This applies to the place itself, not to a
    /// pointer value. This is inserted by rustc in a single case: slice patterns.
    /// ```text
    /// fn slice_pattern_4(x: &[()]) {
    ///     match x {
    ///         [_named] => (),
    ///         _ => (),
    ///     }
    /// }
    /// ```
    Len(Place, Ty, Option<ConstantExpr>),
    /// `Repeat(x, n)` creates an array where `x` is copied `n` times.
    ///
    /// We translate this to a function call for LLBC.
    Repeat(Operand, Ty, ConstantExpr),
}

#[derive(
    Debug,
    PartialEq,
    Eq,
    Clone,
    EnumIsA,
    EnumToGetters,
    EnumAsGetters,
    VariantName,
    SerializeState,
    DeserializeState,
    Drive,
    DriveMut,
    DriveTwo,
)]
#[serde_state(state_implements = DedupSerializerState)] // Avoid corecursive impls due to perfect derive
pub enum Operand {
    Copy(Place),
    Move(Place),
    /// Constant value (including constant and static variables)
    #[cfg_attr(feature = "charon_on_charon", charon::rename("Constant"))]
    Const(ConstantExpr),
}

/// Used for [`Rvalue::Use`] to indicate whether the operand should be retagged (this is used
/// for Rust's aliasing model).
#[derive(
    Debug, Hash, PartialEq, Eq, Clone, SerializeState, DeserializeState, Drive, DriveMut, DriveTwo,
)]
#[cfg_attr(feature = "charon_on_charon", charon::variants_suffix("Retag"))]
pub enum WithRetag {
    No,
    Yes,
}

#[derive(Debug, PartialEq, Eq, Copy, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "charon_on_charon", charon::variants_prefix("O"))]
pub enum OverflowMode {
    /// If this operation overflows, it panics. Only exists in debug mode, for instance in
    /// `a + b`, and only if `--reconstruct-fallible-operations` is passed to Charon. Otherwise the
    /// bound check will be explicit.
    Panic,
    /// If this operation overflows, it is UB; for instance in `core::num::unchecked_add`. This can
    /// exists in safe code, but will always be preceded by a bounds check.
    UB,
    /// If this operation overflows, it wraps around for instance in `core::num::wrapping_add`,
    /// or `a + b` in release mode.
    Wrap,
}

/// Binary operations.
#[derive(
    Debug,
    PartialEq,
    Eq,
    Copy,
    Clone,
    EnumIsA,
    VariantName,
    SerializeState,
    DeserializeState,
    Drive,
    DriveMut,
    DriveTwo,
)]
#[cfg_attr(feature = "charon_on_charon", charon::rename("Binop"))]
#[serde_state(stateless)]
pub enum BinOp {
    BitXor,
    BitAnd,
    BitOr,
    Eq,
    Lt,
    Le,
    Ne,
    Ge,
    Gt,
    Add(OverflowMode),
    Sub(OverflowMode),
    Mul(OverflowMode),
    Div(OverflowMode),
    Rem(OverflowMode),
    /// Returns `(result, did_overflow)`, where `result` is the result of the operation with
    /// wrapping semantics, and `did_overflow` is a boolean that indicates whether the operation
    /// overflowed. This operation does not fail.
    AddChecked,
    /// Like `AddChecked`.
    SubChecked,
    /// Like `AddChecked`.
    MulChecked,
    /// Fails if the shift is bigger than the bit-size of the type.
    Shl(OverflowMode),
    /// Fails if the shift is bigger than the bit-size of the type.
    Shr(OverflowMode),
    /// `BinOp(Offset, ptr, n)` for `ptr` a pointer to type `T` offsets `ptr` by `n * size_of::<T>()`.
    Offset,
    /// `BinOp(Cmp, a, b)` returns `-1u8` if `a < b`, `0u8` if `a == b`, and `1u8` if `a > b`.
    Cmp,
}

/// Unary operation
#[derive(
    Debug,
    PartialEq,
    Eq,
    Clone,
    EnumIsA,
    VariantName,
    SerializeState,
    DeserializeState,
    Drive,
    DriveMut,
    DriveTwo,
)]
#[cfg_attr(feature = "charon_on_charon", charon::rename("Unop"))]
pub enum UnOp {
    Not,
    /// This can overflow, for `-i::MIN`.
    #[serde_state(stateless)]
    Neg(OverflowMode),
    /// Casts are rvalues in MIR, but we treat them as unops.
    Cast(CastKind),
}

/// For all the variants: the first type gives the source type, the second one gives
/// the destination type.
#[derive(
    Debug,
    PartialEq,
    Eq,
    Clone,
    EnumIsA,
    VariantName,
    SerializeState,
    DeserializeState,
    Drive,
    DriveMut,
    DriveTwo,
)]
#[cfg_attr(feature = "charon_on_charon", charon::variants_prefix("Cast"))]
pub enum CastKind {
    /// Conversion between types in `{Integer, Bool}`
    /// Remark: for now we don't support conversions with Char.
    Scalar(LiteralTy, LiteralTy),
    RawPtr(Ty, Ty),
    FnPtr(Ty, Ty),
    /// [Unsize coercion](https://doc.rust-lang.org/std/ops/trait.CoerceUnsized.html). This is
    /// either `[T; N]` -> `[T]` or `T: Trait` -> `dyn Trait` coercions, behind a pointer
    /// (reference, `Box`, or other type that implements `CoerceUnsized`).
    ///
    /// The special case of `&[T; N]` -> `&[T]` coercion is caught by `UnOp::ArrayToSlice`.
    Unsize(Ty, Ty, UnsizingMetadata),
    /// Reinterprets the bits of a value of one type as another type, i.e. exactly what
    /// [`std::mem::transmute`] does.
    Transmute(Ty, Ty),
    /// Converts a receiver type with `dyn Trait<...>` to a concrete type `T`, used in vtable method shims.
    /// Valid conversions are references, raw pointers, and (optionally) boxes:
    /// - `&[mut] dyn Trait<...>` -> `&[mut] T`
    /// - `*[mut] dyn Trait<...>` -> `*[mut] T`
    /// - `Box<dyn Trait<...>>` -> `Box<T>` when no `--raw-boxes`
    ///
    /// For possible receivers, see: <https://doc.rust-lang.org/reference/items/traits.html#dyn-compatibility>.
    /// Other receivers, e.g., `Rc` should be unpacked before the cast and re-boxed after.
    /// FIXME(ssyram): but this is not implemented yet, namely, there may still be
    ///     something like `Rc<dyn Trait<...>> -> Rc<T>` in the types.
    Concretize(Ty, Ty),
}

/// Nullary operation
#[derive(
    Debug,
    PartialEq,
    Eq,
    Clone,
    EnumIsA,
    VariantName,
    SerializeState,
    DeserializeState,
    Drive,
    DriveMut,
    DriveTwo,
)]
#[cfg_attr(feature = "charon_on_charon", charon::rename("Nullop"))]
pub enum NullOp {
    SizeOf,
    AlignOf,
    OffsetOf(TypeDeclRef, Option<VariantId>, FieldId),
    UbChecks,
    OverflowChecks,
    ContractChecks,
}

#[derive(
    Debug,
    PartialEq,
    Eq,
    Copy,
    Clone,
    EnumIsA,
    EnumAsGetters,
    Serialize,
    Deserialize,
    Drive,
    DriveMut,
    DriveTwo,
)]
#[cfg_attr(feature = "charon_on_charon", charon::variants_prefix("B"))]
pub enum BorrowKind {
    Shared,
    Mut,
    /// See <https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/mir/enum.MutBorrowKind.html#variant.TwoPhaseBorrow>
    /// and <https://rustc-dev-guide.rust-lang.org/borrow_check/two_phase_borrows.html>
    TwoPhaseMut,
    /// Those are typically introduced when using guards in matches, to make sure guards don't
    /// change the variant of an enum value while me match over it.
    ///
    /// See <https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/mir/enum.FakeBorrowKind.html#variant.Shallow>.
    Shallow,
    /// Data must be immutable but not aliasable. In other words you can't mutate the data but you
    /// can mutate *through it*, e.g. if it points to a `&mut T`. This is only used in closure
    /// captures, e.g.
    /// ```rust,ignore
    /// let mut z = 3;
    /// let x: &mut isize = &mut z;
    /// let y = || *x += 5;
    /// ```
    /// Here the captured variable can't be `&mut &mut x` since the `x` binding is not mutable, yet
    /// we must be able to mutate what it points to.
    ///
    /// See <https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/mir/enum.MutBorrowKind.html#variant.ClosureCapture>.
    UniqueImmutable,
}

#[derive(
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Clone,
    EnumIsA,
    VariantName,
    SerializeState,
    DeserializeState,
    Drive,
    DriveMut,
    DriveTwo,
    Hash,
)]
#[cfg_attr(feature = "charon_on_charon", charon::variants_prefix("Meta"))]
pub enum UnsizingMetadata {
    /// Cast from `[T; N]` to `[T]`.
    Length(ConstantExpr),
    /// Cast from a sized value to a `dyn Trait` value. The `TraitRef` is the proof of the `dyn
    /// Trait` predicate; the constant expression is a reference to the vtable `static` value.
    VTable(TraitRef, ConstantExpr),
    /// Cast from `dyn Trait` to `dyn OtherTrait`. The fields indicate how to retreive the vtable:
    /// it's always either the same we already had, or the vtable for a (possibly nested) supertrait.
    ///
    /// Note that we cheat in one case: when upcasting to a marker trait (e.g. `dyn Trait -> dyn
    /// Sized`), we keep the current vtable.
    VTableUpcast(Vec<FieldId>),
    Unknown,
}

/// An aggregated ADT.
///
/// Note that ADTs are desaggregated at some point in MIR. For instance, if
/// we have in Rust:
/// ```ignore
///   let ls = Cons(hd, tl);
/// ```
///
/// In MIR we have (yes, the discriminant update happens *at the end* for some
/// reason):
/// ```text
///   (ls as Cons).0 = move hd;
///   (ls as Cons).1 = move tl;
///   discriminant(ls) = 0; // assuming `Cons` is the variant of index 0
/// ```
///
/// Rem.: in the Aeneas semantics, both cases are handled (in case of desaggregated
/// initialization, `ls` is initialized to `⊥`, then this `⊥` is expanded to
/// `Cons (⊥, ⊥)` upon the first assignment, at which point we can initialize
/// the field 0, etc.).
#[derive(
    Debug,
    PartialEq,
    Eq,
    Clone,
    VariantIndexArity,
    SerializeState,
    DeserializeState,
    Drive,
    DriveMut,
    DriveTwo,
)]
#[cfg_attr(feature = "charon_on_charon", charon::variants_prefix("Aggregated"))]
pub enum AggregateKind {
    /// A struct, enum or union aggregate. The `VariantId`, if present, indicates this is an enum
    /// and the aggregate uses that variant. The `FieldId`, if present, indicates this is a union
    /// and the aggregate writes into that field. Otherwise this is a struct.
    Adt(TypeDeclRef, Option<VariantId>, Option<FieldId>),
    /// We don't put this with the ADT cas because this is the only built-in type
    /// with aggregates, and it is a primitive type. In particular, it makes
    /// sense to treat it differently because it has a variable number of fields.
    Array(Ty, ConstantExpr),
    /// Construct a raw pointer from a pointer value, and its metadata (can be unit, if building
    /// a thin pointer). The type is the type of the pointee.
    /// We lower this to a builtin function call for LLBC in [crate::transform::simplify_output::ops_to_function_calls].
    RawPtr(Ty, RefKind),
}

impl Rvalue {
    pub fn unit_value() -> Self {
        Rvalue::Aggregate(
            AggregateKind::Adt(
                TypeDeclRef {
                    id: TypeDeclId::UNIT,
                    generics: Box::new(GenericArgs::empty()),
                    builtin: Some(BuiltinTy::Tuple),
                },
                None,
                None,
            ),
            Vec::new(),
        )
    }
}

impl Operand {
    pub fn mk_const_unit() -> Self {
        Operand::Const(ConstantExpr::mk_unit())
    }

    pub fn ty(&self) -> &Ty {
        match self {
            Operand::Copy(place) | Operand::Move(place) => place.ty(),
            Operand::Const(constant_expr) => constant_expr.ty(),
        }
    }
}

impl BorrowKind {
    pub fn mutable(x: bool) -> Self {
        if x { Self::Mut } else { Self::Shared }
    }
}

impl BinOp {
    pub fn with_overflow(&self, overflow: OverflowMode) -> Self {
        match self {
            BinOp::Add(_) | BinOp::AddChecked => BinOp::Add(overflow),
            BinOp::Sub(_) | BinOp::SubChecked => BinOp::Sub(overflow),
            BinOp::Mul(_) | BinOp::MulChecked => BinOp::Mul(overflow),
            BinOp::Div(_) => BinOp::Div(overflow),
            BinOp::Rem(_) => BinOp::Rem(overflow),
            BinOp::Shl(_) => BinOp::Shl(overflow),
            BinOp::Shr(_) => BinOp::Shr(overflow),
            _ => {
                panic!(
                    "Cannot set overflow mode for this binary operator: {:?}",
                    self
                );
            }
        }
    }
}

impl UnOp {
    pub fn with_overflow(&self, overflow: OverflowMode) -> Self {
        match self {
            UnOp::Neg(_) => UnOp::Neg(overflow),
            _ => {
                panic!(
                    "Cannot set overflow mode for this unary operator: {:?}",
                    self
                );
            }
        }
    }
}

impl From<BorrowKind> for RefKind {
    fn from(value: BorrowKind) -> Self {
        match value {
            BorrowKind::Shared | BorrowKind::Shallow => RefKind::Shared,
            BorrowKind::Mut | BorrowKind::TwoPhaseMut | BorrowKind::UniqueImmutable => RefKind::Mut,
        }
    }
}

impl From<RefKind> for BorrowKind {
    fn from(value: RefKind) -> Self {
        match value {
            RefKind::Shared => BorrowKind::Shared,
            RefKind::Mut => BorrowKind::Mut,
        }
    }
}
