[package]
name = "macros"
version = "0.1.0"
authors = ["Son Ho <hosonmarc@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.73"
quote = "1.0.9"
serde = { version = "1.0.117", features = ["derive"] }
toml = "0.5.8"