[package]
name = "macros"
version = "0.1.0"
authors = ["Son Ho <hosonmarc@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.102"
quote = "1.0.21"
serde = { version = "1.0.145", features = ["derive"] }
toml = "0.5.9"
