  $ ../e2e.exe ./cases
  ./cases/paper.llbc parsed correctly
  ./cases/loops.llbc parsed correctly
  ./cases/no_nested_borrows.llbc parsed correctly
  ./cases/hashmap_main.llbc parsed correctly
  ./cases/matches_duplicate.llbc parsed correctly
  ./cases/matches.llbc parsed correctly
  ./cases/hashmap.llbc parsed correctly
  ./cases/external.llbc parsed correctly
  ./cases/nested_borrows.llbc parsed correctly
