//! `panic!()` expands to:
//! ```ignore
//! fn panic_cold_explicit() -> ! {
//!     core::panicking::panic_explicit()
//! }
//! panic_cold_explicit()
//! ```
//! Which defines a new function each time. This pass recognizes these functions and replaces calls
//! to them by a `Panic` terminator.
use std::collections::HashSet;

use crate::transform::CowBox;
use crate::transform::{TransformCtx, ctx::FusedUllbcPass};
use crate::{builtins, names::Name, ullbc_ast::*};

pub struct Transform {
    panic_fns: HashSet<FunDeclId>,
    panic_terminator: TerminatorKind,
}

impl Transform {
    pub fn new(ctx: &mut TransformCtx) -> CowBox<dyn FusedUllbcPass> {
        let panic_name = Name::from_path(builtins::EXPLICIT_PANIC_NAME);
        let panic_terminator = TerminatorKind::Abort(AbortKind::Panic(Some(panic_name)));

        // Collect and remove the functions that were generated by the `panic!` macro.
        let panic_fns: HashSet<FunDeclId> = ctx
            .translated
            .fun_decls
            .extract(|_, decl| {
                decl.body.as_unstructured().is_some_and(|body| {
                    // If the whole body is only a call to this specific panic function.
                    // FIXME: also check that the name of the function is `panic_cold_explicit`?
                    body.body.len() == 1 && {
                        let block = &body.body[0];
                        block.statements.is_empty() && block.terminator.kind == panic_terminator
                    }
                })
            })
            .map(|(id, _)| id)
            .collect();

        CowBox::Owned(Box::new(Transform {
            panic_fns,
            panic_terminator,
        }))
    }
}

impl FusedUllbcPass for Transform {
    fn transform_body(&self, _ctx: &mut TransformCtx, body: &mut ullbc_ast::ExprBody) {
        // Replace each call to one such function with an `Abort`.
        for block in &mut body.body {
            if let TerminatorKind::Call {
                call:
                    Call {
                        func:
                            FnOperand::Regular(FnPtr {
                                kind: fn_ptr_kind, ..
                            }),
                        ..
                    },
                on_unwind: _, // TODO: shouldn't we use this?
                ..
            } = &block.terminator.kind
                && let FnPtrKind::Fun(FunId::Regular(fun_id)) = fn_ptr_kind.as_ref()
                && self.panic_fns.contains(fun_id)
            {
                block.terminator.kind = self.panic_terminator.clone();
            }
        }
    }
}
