name: build-and-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Setup Rust toolchain"
      uses: actions-rs/toolchain@v1
    - name: "build rs"
      run: make
    - name: "test rs"
      run: make test