name: "Build and test"

on:
  # Run the checks on the latest commit from `main`
  push:
    branches:
      - main
  # Run the check for any pull request. The check is run on a merge between the
  # PR commit and the `main` branch at the time of running the check.
  pull_request:
  # Runs the check when a PR is added to the merge queue.
  merge_group:
  # Makes it possible to run the workflow by hand from GitHub's interface.
  workflow_dispatch:

# Cancel previous versions of this job that are still running.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  HAS_CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN != '' }}

jobs:
  select-runner:
    uses: ./.github/workflows/select-runner.yml

  charon:
    needs: [select-runner]
    runs-on: ${{ fromJSON(needs.select-runner.outputs.runs_on) }}
    steps:
      - &install_nix # YAML anchor for deduplication
        name: Install Nix
        if: ${{ runner.environment == 'github-hosted' }}
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://hacl.cachix.org
            extra-trusted-public-keys = hacl.cachix.org-1:FzsZ2xsByOwKwIWNPII7yMOelJNDZ12mDAj3d1eGX0c=
      - &setup_cachix_push
        name: Set up Cachix push
        if: ${{ runner.environment == 'github-hosted' && env.HAS_CACHIX_AUTH_TOKEN == 'true' }}
        uses: cachix/cachix-action@v17
        with:
          name: hacl
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipAddingSubstituter: true
      - uses: actions/checkout@v4
      - run: nix build -L .#charon
      - run: nix build -L .#charon-portable
      - run: nix build -L .#charon-ml
      - run: nix flake check -L

  check-version-number:
    needs: [select-runner]
    runs-on: ${{ fromJSON(needs.select-runner.outputs.runs_on) }}
    steps:
      - *install_nix
      - *setup_cachix_push
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # deep clone in order to get access to other commits
      - run: nix develop '.#ci' --command ./scripts/ci-check-version-number.sh

  # Choose which commit to use for each project. By default we use the latest
  # from the main branch, but this can be overridden with a command in the PR
  # description.
  select-dep-versions:
    needs: [select-runner, charon]
    runs-on: ${{ fromJSON(needs.select-runner.outputs.runs_on) }}
    env:
      CI_EVENT: ${{ github.event_name }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - *install_nix
      - *setup_cachix_push
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # deep clone in order to get access to other commits
      - id: select
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "charon=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          nix develop '.#ci' --command ./scripts/ci-select-dep-versions.py >> "$GITHUB_OUTPUT"
          echo
          echo "Selected the following versions for dependent projects:"
          cat "$GITHUB_OUTPUT"
    outputs:
      charon: ${{ steps.select.outputs.charon }}
      aeneas: ${{ steps.select.outputs.aeneas }}
      eurydice: ${{ steps.select.outputs.eurydice }}
      libcrux: ${{ steps.select.outputs.libcrux }}

  aeneas:
    needs: [select-runner, charon, select-dep-versions]
    runs-on: ${{ fromJSON(needs.select-runner.outputs.runs_on) }}
    steps:
      - *install_nix
      - *setup_cachix_push
      - uses: actions/checkout@v4
        with:
          repository: Inria-Prosecco/circus-green
      - env:
          CHARON: ${{needs.select-dep-versions.outputs.charon}}
          AENEAS: ${{needs.select-dep-versions.outputs.aeneas}}
        run: |
          echo 'Using the aeneas commit selected by `select-dep-versions`'
          nix flake update --refresh \
              charon aeneas \
              --override-input charon github:aeneasverif/charon/$CHARON \
              --override-input aeneas github:aeneasverif/aeneas/$AENEAS
          ./check.sh aeneas

  eurydice:
    needs: [select-runner, charon, select-dep-versions]
    runs-on: ${{ fromJSON(needs.select-runner.outputs.runs_on) }}
    steps:
      - *install_nix
      - *setup_cachix_push
      - uses: actions/checkout@v4
        with:
          repository: Inria-Prosecco/circus-green
      - env:
          CHARON: ${{needs.select-dep-versions.outputs.charon}}
          EURYDICE: ${{needs.select-dep-versions.outputs.eurydice}}
        run: |
          echo 'Using the eurydice commit selected by `select-dep-versions`'
          nix flake update --refresh \
              charon eurydice \
              --override-input charon github:aeneasverif/charon/$CHARON \
              --override-input eurydice github:aeneasverif/eurydice/$EURYDICE
          ./check.sh eurydice
