# On each push to `main`, this restarts all the workflow runs associated with
# open PRs, to ensure they're always up-to-date.
name: "Rerun PR jobs on push to main"

on:
  # Triggered when commits are added to the `main` branch.
  push:
    branches:
      - main
  # Makes it possible to run the forkflow by hand from GitHub's interface.
  workflow_dispatch:

permissions:
  actions: write
  checks: write

jobs:
  rerun-pr-jobs-on-push:
    runs-on: [self-hosted, linux, nix]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: nix develop '.#ci' --command ./scripts/ci-rerun-pr-jobs.sh
