on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  rustc-tests:
    runs-on: [self-hosted, linux, nix]
    steps:
      - uses: actions/checkout@v4
      - run: |
          nix build -L '.#rustc-tests'
          echo "Summary of the results:" > message.txt
          echo '```text' >> message.txt
          cat result/charon-summary >> message.txt
          echo '```' >> message.txt
          cat result/charon-grouped-results >> message.txt
      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('node:fs');
            const message = fs.readFileSync('./message.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: 145,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message,
            });
