on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.13.1
      - run: opam install . --deps-only
      - run: opam install ocamlformat odoc
      - run: opam exec -- make build
      - run: IN_CI=1 opam exec -- make test
